version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: xiaomo
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: xiaomo
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.2
    - 1.440.4
    - 1.441.0
    - 1.445.0
    - 1.446.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.463.0
    - 1.464.0
    - 1.467.0
    - 1.471.0
    - 1.476.0
    - 1.477.0
    - 1.479.0
    - 1.483.0
    - 1.487.0
    - 1.490.0
    - 1.493.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.506.0
    - 1.509.0
    - 1.512.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.529.0
    - 1.531.0
    - 1.534.0
    - 1.539.0
    - 1.542.0
    - 1.559.0
    - 1.563.0
    - 1.564.0
    - 1.567.0
    - 1.570.0
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
    - 8.24.3
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
